// EDITAR AQUI: os textos completos ficam em content.json; fotos podem substituir os espaços em assets/images.
const escapeHtml=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slugify=s=>s.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/(^-|-$)/g,'');
function placeholder(label,sub='EDITAR AQUI · substituir pelo arquivo real',src=''){return `<div class="placeholder" role="img" aria-label="${escapeHtml(label)} — ${escapeHtml(sub)}">${src?`<img loading="lazy" src="${src}" alt="${escapeHtml(sub)}" onerror="this.remove()">`:''}<strong>${escapeHtml(label)}</strong><small>${escapeHtml(sub)}</small></div>`}
function textBlocks(raw){let lines=raw.split('\n'),out='',block=[];const flush=()=>{if(block.length){out+=`<p>${escapeHtml(block.join('\n'))}</p>`;block=[]}};for(const line of lines){const t=line.trim();if(!t){flush();continue}if(/^(❤️|🌷|💜|🕊️|👶🏻|📚|🌱|💭|🤾🏻‍♀️|👨‍👩‍👧‍👦|🏫|🧩|🔎|🧪)/u.test(t)){flush();out+=`<h3>${escapeHtml(t)}</h3>`}else if(/^\d+\. /.test(t)&&raw.includes('Substâncias pesquisadas')){flush();out+=`<h5>${escapeHtml(t)}</h5>`}else if(t.startsWith('- ')){flush();out+=`<p>${escapeHtml(t)}</p>`}else block.push(t)}flush();return out}
function gallery(count,prefix,cls=''){return `<div class="gallery ${cls}">${Array.from({length:count},(_,i)=>`<div class="gallery-item" data-label="${prefix} ${String(i+1).padStart(2,'0')}">${placeholder('ADICIONAR FOTO',`${prefix} ${String(i+1).padStart(2,'0')}`,`assets/images/trabalhos/${prefix}-${String(i+1).padStart(2,'0')}.jpg`)}</div>`).join('')}</div>`}
fetch('content.json').then(r=>r.json()).then(data=>{
const profiles=data.profiles;document.querySelector('#peopleCards').innerHTML=profiles.map(p=>`<article class="person-card">${placeholder('ADICIONAR FOTO',`Retrato de ${p.name}`,`assets/images/integrantes/${p.slug}/${p.slug}-01.jpg`)}<div class="person-card-info"><h3>${escapeHtml(p.name)}</h3><p>TRAJETÓRIA PESSOAL</p><a class="card-link" href="#perfil-${p.slug}">Conhecer minha história ↗</a></div></article>`).join('');
document.querySelector('#profiles').innerHTML=profiles.map((p,i)=>{const facts=p.body.split('\n').filter(x=>/^(Data de nascimento:|Idade:|Cidade onde nasci:|Dia da semana em que nasci:|Horário de nascimento:|Cidade natal:|Cidade onde moro atualmente:)/.test(x));const body=p.body.split('\n').filter(x=>!facts.includes(x)).join('\n');return `<article class="profile" id="perfil-${p.slug}"><aside class="profile-aside"><div class="section-label">0${i+1} / INTEGRANTE</div><h2>${escapeHtml(p.name)}</h2>${placeholder('ADICIONAR FOTO',`Retrato de ${p.name}`,`assets/images/integrantes/${p.slug}/${p.slug}-01.jpg`)}<ul class="meta">${facts.map(f=>`<li>${escapeHtml(f)}</li>`).join('')}</ul><div class="carousel" data-total="5" data-current="1">${placeholder('ADICIONAR FOTO',`${p.slug}-01.jpg`)}<div class="carousel-controls"><button class="round-button prev" aria-label="Foto anterior">←</button><span class="count">1 / 5</span><button class="round-button next" aria-label="Próxima foto">→</button></div></div></aside><div class="profile-copy">${textBlocks(body)}</div></article>`}).join('');
document.querySelector('#workList').innerHTML=data.works.map(w=>{let body=w.body;let galleryHtml='';if(w.slug==='1708')galleryHtml=gallery(3,'trabalho-1708','');if(w.slug==='0209')galleryHtml=gallery(1,'trabalho-0209','');if(w.slug==='1609')galleryHtml=['dayane','leticia','thayna'].map(n=>`<h5>${n.toUpperCase()}</h5>${gallery(2,`${n}-mapa`,'two')}`).join('');let intro='';if(w.slug==='1208'){let k=body.indexOf('Substâncias pesquisadas');if(k>=0){intro=textBlocks(body.slice(0,k));const chunk=body.slice(k).split('\n');const cards=[];for(let i=0;i<chunk.length;i++){if(/^\d+\. /.test(chunk[i])){let name=chunk[i].replace(/^\d+\. /,'');let vals=[];for(let j=i+1;j<chunk.length&&!/^\d+\. /.test(chunk[j]);j++)if(chunk[j].trim())vals.push(chunk[j]);cards.push(`<div class="substance"><b>${escapeHtml(name)}</b>${vals.map(v=>`<span>${escapeHtml(v)}</span>`).join('')}</div>`)}}body=`<h5>Substâncias pesquisadas</h5><div class="substances">${cards.join('')}</div>`}else body=textBlocks(body)}else body=textBlocks(body);return `<article class="work-card"><div class="work-date">${escapeHtml(w.date.toUpperCase())}</div><h3>${escapeHtml(w.title)}</h3>${w.subtitle?`<h4>${escapeHtml(w.subtitle)}</h4>`:''}<div class="work-copy">${intro}${body}</div>${galleryHtml}</article>`}).join('')+`<article class="work-card future"><div class="work-date">EDITAR AQUI</div><h3>PRÓXIMO TRABALHO</h3><p class="future-fields">Data · título · texto · fotos · descrição · resultados</p><p>Espaço reservado para adicionar um novo trabalho.</p></article>`;
init();}).catch(err=>{document.querySelector('#workList').innerHTML='<p>Não foi possível carregar content.json.</p>';console.error(err)});
function init(){const toggle=document.querySelector('#menuToggle'),nav=document.querySelector('#nav');toggle.onclick=()=>{let open=nav.classList.toggle('open');toggle.setAttribute('aria-expanded',open)};nav.querySelectorAll('a').forEach(a=>a.onclick=()=>nav.classList.remove('open'));const top=document.querySelector('#toTop');window.addEventListener('scroll',()=>top.classList.toggle('show',scrollY>500));top.onclick=()=>scrollTo({top:0,behavior:'smooth'});document.querySelectorAll('.carousel').forEach(c=>{let n=1;const label=c.dataset.total;const update=()=>{c.querySelector('.count').textContent=`${n} / ${label}`;c.querySelector('.placeholder').outerHTML=placeholder('ADICIONAR FOTO',`${c.closest('.profile').id.replace('perfil-','')}-${String(n).padStart(2,'0')}.jpg`);bindLightbox()};c.querySelector('.prev').onclick=()=>{n=n===1?5:n-1;update()};c.querySelector('.next').onclick=()=>{n=n===5?1:n+1;update()};let x=0;c.addEventListener('touchstart',e=>x=e.touches[0].clientX,{passive:true});c.addEventListener('touchend',e=>{let d=e.changedTouches[0].clientX-x;if(Math.abs(d)>45){n=((n-1+(d<0?1:4))%5)+1;update()}},{passive:true})});bindLightbox()}
function bindLightbox(){const box=document.querySelector('#lightbox'),content=box.querySelector('.lightbox-content');document.querySelectorAll('.placeholder').forEach(el=>{if(el.dataset.bound)return;el.dataset.bound='1';el.tabIndex=0;el.onclick=()=>{content.innerHTML=el.outerHTML;box.classList.add('open')};el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();el.click()}}});box.querySelector('.lightbox-close').onclick=()=>box.classList.remove('open');box.onclick=e=>{if(e.target===box)box.classList.remove('open')};document.addEventListener('keydown',e=>{if(e.key==='Escape')box.classList.remove('open')},{once:true})}
